/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fee_management;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author nikhil
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
    }
    
    public void getRecords(){
        try{
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ManageZilla","root","");
          PreparedStatement pst=con.prepareStatement("Select *from fees_details order by receipt_no Desc limit 1");
          ResultSet rs=pst.executeQuery();
          rs.next();
          txt_receiptNo.setText(rs.getString("receipt_no"));
          txt_PaymentMode.setText(rs.getString("payment_mode"));
          String PaymentMode=rs.getString("payment_mode");
          if(PaymentMode.equalsIgnoreCase("cash")){
              lbl_cheque_dd.setText("Cheque No");
              txt_cheque_dd.setText("-");
              txt_bankname.setText("-");
          }
          
          if(PaymentMode.equalsIgnoreCase("cheque")){
              lbl_cheque_dd.setText("Cheque No");
              txt_cheque_dd.setText(rs.getString("cheque_no"));
              txt_bankname.setText(rs.getString("bank_name"));
          }
          
          if(PaymentMode.equalsIgnoreCase("dd")){
              lbl_cheque_dd.setText("DD No");
              txt_cheque_dd.setText(rs.getString("dd_no"));
              txt_bankname.setText(rs.getString("bank_name"));
          }
          if(PaymentMode.equalsIgnoreCase("Credit card")){
              lbl_cheque_dd.setText("Transaction ID:-");
              txt_cheque_dd.setText(rs.getString("transaction_Id"));
              txt_bankname.setText(rs.getString("bank_name"));
          }
          if(PaymentMode.equalsIgnoreCase("Debit card")){
              lbl_cheque_dd.setText("Transaction ID");
              txt_cheque_dd.setText(rs.getString("transaction_Id"));
              txt_bankname.setText(rs.getString("bank_name"));
          }
          txt_sno.setText(rs.getString("receipt_no"));
          txt_courseName.setText(rs.getString("course_name"));
          txt_receivedfrom.setText(rs.getString("student_name"));
          txt_date.setText(rs.getString("date"));
          txt_month1.setText(rs.getString("year1"));
          txt_month2.setText(rs.getString("year2"));
          
          txt_amount.setText(rs.getString("amount"));
          txt_cgst.setText(rs.getString("cgst"));
          txt_sgst.setText(rs.getString("sgst"));
          txt_totalAmt.setText(rs.getString("total_amount"));
          txt_Amountinwords.setText(rs.getString("total_in_words"));
          txt_remark.setText(rs.getString("remark"));
          
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        btn_home = new javax.swing.JLabel();
        panelsearch = new javax.swing.JPanel();
        btn_search = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        btn_editcourse = new javax.swing.JLabel();
        panelcourselist = new javax.swing.JPanel();
        btn_courselist = new javax.swing.JLabel();
        panelallrecord = new javax.swing.JPanel();
        btn_allrecord = new javax.swing.JLabel();
        panelback = new javax.swing.JPanel();
        btn_back = new javax.swing.JLabel();
        panellogout = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        panelPrint = new javax.swing.JPanel();
        btn_printIt = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_PaymentMode = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_receivedfrom = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_month1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_month2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_sno = new javax.swing.JLabel();
        txt_courseName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txt_totalAmt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_Amountinwords = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 255, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(109, 203, 246));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelhome.setBackground(new java.awt.Color(184, 229, 250));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhomeMouseEntered(evt);
            }
        });

        btn_home.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/home.png"))); // NOI18N
        btn_home.setText("  Home");
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_home))
        );

        jPanel1.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 300, -1));

        panelsearch.setBackground(new java.awt.Color(184, 229, 250));
        panelsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelsearch.setPreferredSize(new java.awt.Dimension(146, 54));

        btn_search.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/search.png"))); // NOI18N
        btn_search.setText("Search Record");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelsearchLayout = new javax.swing.GroupLayout(panelsearch);
        panelsearch.setLayout(panelsearchLayout);
        panelsearchLayout.setHorizontalGroup(
            panelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelsearchLayout.setVerticalGroup(
            panelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_search))
        );

        jPanel1.add(panelsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, -1));

        paneledit.setBackground(new java.awt.Color(184, 229, 250));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_editcourse.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_editcourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editcourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/edit.png"))); // NOI18N
        btn_editcourse.setText("Update Fees");
        btn_editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editcourseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneleditLayout = new javax.swing.GroupLayout(paneledit);
        paneledit.setLayout(paneleditLayout);
        paneleditLayout.setHorizontalGroup(
            paneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneleditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_editcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneleditLayout.setVerticalGroup(
            paneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneleditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_editcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 300, -1));

        panelcourselist.setBackground(new java.awt.Color(184, 229, 250));
        panelcourselist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_courselist.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_courselist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_courselist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/courselist.png"))); // NOI18N
        btn_courselist.setText("Course List");
        btn_courselist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_courselistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_courselistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_courselistMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelcourselistLayout = new javax.swing.GroupLayout(panelcourselist);
        panelcourselist.setLayout(panelcourselistLayout);
        panelcourselistLayout.setHorizontalGroup(
            panelcourselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcourselistLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_courselist, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelcourselistLayout.setVerticalGroup(
            panelcourselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcourselistLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_courselist))
        );

        jPanel1.add(panelcourselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        panelallrecord.setBackground(new java.awt.Color(184, 229, 250));
        panelallrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_allrecord.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_allrecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_allrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/allrecords.png"))); // NOI18N
        btn_allrecord.setText("View all records");
        btn_allrecord.setToolTipText("");
        btn_allrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_allrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_allrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_allrecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelallrecordLayout = new javax.swing.GroupLayout(panelallrecord);
        panelallrecord.setLayout(panelallrecordLayout);
        panelallrecordLayout.setHorizontalGroup(
            panelallrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelallrecordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_allrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelallrecordLayout.setVerticalGroup(
            panelallrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelallrecordLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_allrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelallrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 300, 60));

        panelback.setBackground(new java.awt.Color(184, 229, 250));
        panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_back.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelbackLayout = new javax.swing.GroupLayout(panelback);
        panelback.setLayout(panelbackLayout);
        panelbackLayout.setHorizontalGroup(
            panelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelbackLayout.setVerticalGroup(
            panelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 300, 60));

        panellogout.setBackground(new java.awt.Color(184, 229, 250));
        panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_logout.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panellogoutLayout = new javax.swing.GroupLayout(panellogout);
        panellogout.setLayout(panellogoutLayout);
        panellogoutLayout.setHorizontalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellogoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panellogoutLayout.setVerticalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellogoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 300, 60));

        panelPrint.setBackground(new java.awt.Color(184, 229, 250));
        panelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_printIt.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_printIt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_printIt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/print.png"))); // NOI18N
        btn_printIt.setText("Print");
        btn_printIt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printItMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printItMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printItMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPrintLayout = new javax.swing.GroupLayout(panelPrint);
        panelPrint.setLayout(panelPrintLayout);
        panelPrintLayout.setHorizontalGroup(
            panelPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrintLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_printIt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrintLayout.setVerticalGroup(
            panelPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrintLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_printIt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 300, -1));

        panelEdit.setBackground(new java.awt.Color(184, 229, 250));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btn_Edit.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        btn_Edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/img_addfees/Edit_it.png"))); // NOI18N
        btn_Edit.setText("Add Fees");
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 300, -1));

        kGradientPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 850));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GLA College");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 240, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nilamber Pitamber University");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 390, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management/npulogo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 130));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Near CRPF Camp , Medininagar, Jharkhand ,822102\n");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 430, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 770, 3));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Receipt No:-  NPU");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txt_receiptNo.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, 20));

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Payment Mode:-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, -1));

        txt_PaymentMode.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_PaymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 150, 20));

        lbl_cheque_dd.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        lbl_cheque_dd.setForeground(new java.awt.Color(0, 0, 153));
        lbl_cheque_dd.setText("Cheque No./DD No./Transaction ID:-");
        jPanel2.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel2.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 20));

        lbl_bankName.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        lbl_bankName.setForeground(new java.awt.Color(0, 0, 153));
        lbl_bankName.setText("Bank Name:-");
        jPanel2.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txt_bankname.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 210, 20));

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Received from:-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txt_receivedfrom.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_receivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 300, 20));

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("The following payment is for the month");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 280, -1));

        txt_month1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_month1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 110, 20));

        jLabel11.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("to");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 20, -1));

        txt_month2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_month2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_month2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 130, 20));

        jLabel13.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Date:-");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        txt_date.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 160, 20));

        jLabel12.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("GSTIN:- AB12C34D");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 190, 20));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 770, 3));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 398, 770, -1));

        jLabel14.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Serial No");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Course Name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("Amount (Rs.)");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        txt_sno.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_sno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_sno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, 30));

        txt_courseName.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_courseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 220, 30));

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("CGST:- 9%");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("SGST:- 9%");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        txt_amount.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 200, 20));

        txt_cgst.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_cgst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 180, 20));

        txt_sgst.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_sgst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 190, 20));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 290, 10));

        jLabel20.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Total :-");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        txt_totalAmt.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        txt_totalAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txt_totalAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 190, 30));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 290, 10));

        jLabel22.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 153));
        jLabel22.setText("Receiver's Signature");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 710, -1, -1));

        jLabel21.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Total in words :-");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        txt_Amountinwords.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_Amountinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 540, 20));

        jLabel24.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 153));
        jLabel24.setText("Remark:-");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        txt_remark.setFont(new java.awt.Font("Imprint MT Shadow", 0, 16)); // NOI18N
        jPanel2.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 690, 300, 30));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("* This is Computer generated receipt.");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 760, 430, -1));

        kGradientPanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 770, 790));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Print Receipt");
        kGradientPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 220, -1));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        home home_page= new home();
        home_page.show();
        this.dispose();

    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr = new Color(0,255,165);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr = new Color(184,229,250);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void panelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseEntered

    }//GEN-LAST:event_panelhomeMouseEntered

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        Color clr = new Color(0,255,165);
        panelsearch.setBackground(clr);
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        Color clr = new Color(184,229,250);
        panelsearch.setBackground(clr);
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseEntered
        Color clr = new Color(0,255,165);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_btn_editcourseMouseEntered

    private void btn_editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseExited
        Color clr = new Color(184,229,250);
        paneledit.setBackground(clr);
    }//GEN-LAST:event_btn_editcourseMouseExited

    private void btn_courselistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_courselistMouseEntered
        Color clr = new Color(0,255,165);
        panelcourselist.setBackground(clr);
    }//GEN-LAST:event_btn_courselistMouseEntered

    private void btn_courselistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_courselistMouseExited
        Color clr = new Color(184,229,250);
        panelcourselist.setBackground(clr);
    }//GEN-LAST:event_btn_courselistMouseExited

    private void btn_allrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_allrecordMouseEntered
        Color clr = new Color(0,255,165);
        panelallrecord.setBackground(clr);
    }//GEN-LAST:event_btn_allrecordMouseEntered

    private void btn_allrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_allrecordMouseExited
        Color clr = new Color(184,229,250);
        panelallrecord.setBackground(clr);
    }//GEN-LAST:event_btn_allrecordMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        Color clr = new Color(0,255,165);
        panelback.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        Color clr = new Color(184,229,250);
        panelback.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        Color clr = new Color(0,255,165);
        panellogout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        Color clr = new Color(184,229,250);
        panellogout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_printItMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printItMouseEntered
        Color clr = new Color(0,255,165);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btn_printItMouseEntered

    private void btn_printItMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printItMouseExited
        Color clr = new Color(184,229,250);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btn_printItMouseExited

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered
        Color clr = new Color(0,255,165);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btn_EditMouseEntered

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        Color clr = new Color(184,229,250);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_printItMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printItMouseClicked
     PrinterJob job=PrinterJob.getPrinterJob();
     job.setJobName("Print Data");
     
     job.setPrintable(new Printable(){
         public int print(Graphics pg, PageFormat pf, int pageNum){
             pf.setOrientation(PageFormat.LANDSCAPE);
             if(pageNum>0){
                 return Printable.NO_SUCH_PAGE;
             }
             Graphics2D g2=(Graphics2D)pg;
             g2.translate(pf.getImageableX(),pf.getImageableY());
             g2.scale(0.47,0.47);
             
             jPanel2.print(g2);
             
             return Printable.PAGE_EXISTS;
         }

     });
     boolean ok =job.printDialog();
     if(ok){
         try{
            job.print(); 
         }catch(PrinterException ex){
             ex.printStackTrace();
         }
     }
    }//GEN-LAST:event_btn_printItMouseClicked

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        Addfees af=new Addfees();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EditMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        SearchRecord sr=new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_editcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editcourseMouseClicked
        UpdateFeesDetails ufd =new UpdateFeesDetails();
        ufd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editcourseMouseClicked

    private void btn_courselistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_courselistMouseClicked
       EditCourse ec=new EditCourse();
       ec.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_courselistMouseClicked

    private void btn_allrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_allrecordMouseClicked
       ViewAllRecords val=new ViewAllRecords();
       val.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_allrecordMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        home Home=new home();
        Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
      Login login =new Login();
      login.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Edit;
    private javax.swing.JLabel btn_allrecord;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_courselist;
    private javax.swing.JLabel btn_editcourse;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_printIt;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelPrint;
    private javax.swing.JPanel panelallrecord;
    private javax.swing.JPanel panelback;
    private javax.swing.JPanel panelcourselist;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panellogout;
    private javax.swing.JPanel panelsearch;
    private javax.swing.JLabel txt_Amountinwords;
    private javax.swing.JLabel txt_PaymentMode;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_courseName;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_month1;
    private javax.swing.JLabel txt_month2;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_receivedfrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_sno;
    private javax.swing.JLabel txt_totalAmt;
    // End of variables declaration//GEN-END:variables
}
